CircleCI: Use Custom Docker Image v2
hyperledger-labs/minbft pull request #49
Opened 2018-11-30 08:22 UTC by ynamiki

Currently, the CI sets up an environment (Go, Intel SGX SDK, etc.) from a fresh Ubuntu image everytime.

This patch introduces a custom Docker image, which contains everything used to build and test our project. By using this image, the CI can skip the environment setup and do just build and test in a CI process; saving resource and time.

Changes from v1 (#48):
- Reorganize commits
- Update the commit comment

2018-11-30 08:27 UTC, nhoriguchi approved these changes
Great, thank you!

2018-11-30 12:39 UTC, sergefdrv commented
@ynamiki Please wait a bit, I would have some comments.

2018-11-30 13:24 UTC, sergefdrv requested changes
Thanks!

2018-11-30 13:24 UTC, sergefdrv commented on .circleci/images/Dockerfile
> +  && echo 'export PATH="/usr/local/go/bin:$PATH"' | sudo tee -a /etc/profile > /dev/null
I was not sure why you use `| tee -a /etc/profile > /dev/null` rather than simply `>> /etc/profile`. Anyways, I would suggest adding this as a separate file in the line 9: `> /etc/profile.d/golang.sh`, then appending to the file with `>>` in the line 10.

2018-11-30 13:24 UTC, sergefdrv commented on .circleci/images/Dockerfile
> +  && echo 'source /opt/intel/sgxsdk/environment' | sudo tee -a /etc/profile > /dev/null
Please also consider changing to `> /etc/profile.d/intel-sgx.sh`.

2018-11-30 13:24 UTC, sergefdrv commented on .circleci/images/Dockerfile
> +RUN echo 'export PATH="$GOPATH/bin:$PATH"' | sudo tee -a /etc/profile > /dev/null
Looks like this belongs to the `RUN` directive on line 7.

2018-11-30 13:24 UTC, sergefdrv commented on .circleci/images/Dockerfile
> +  && echo 'export PATH="/opt/gometalinter-2.0.11-linux-amd64:$PATH"' | sudo tee -a /etc/profile > /dev/null
Please also consider changing to `> /etc/profile.d/gometalinter.sh`.

2018-11-30 13:24 UTC, sergefdrv commented on .circleci/images/Dockerfile
> +  && curl -L $GOMETALINTER_URL | sudo tar -C /opt -xzf - \
Please consider changing it like `tar --strip-components=1 -C /opt/gometalinter/`. Perhaps, we don't need to keep the version suffix in the path.

2018-11-30 13:24 UTC, sergefdrv commented on .circleci/images/Dockerfile
> +  && echo 'source /opt/intel/sgxsdk/environment' | sudo tee -a /etc/profile > /dev/null
I wonder if sourcing the `environment` file is enough? I remember I had to add another config file in `/etc/ld.so.conf.d/` on my machine so that the dynamic linker recognizes the SDK library path (LD_LIBRARY_PATH set in profile is ignored in recent Ubuntu, cf. https://github.com/hyperledger-labs/minbft#intel-sgx-sdk). One could check it in the container by trying one of the sample enclaves installed with SDK.

2018-11-30 15:22 UTC, sergefdrv commented on .circleci/images/Dockerfile
> +  && echo 'export PATH="/usr/local/go/bin:$PATH"' | sudo tee -a /etc/profile > /dev/null
I see, `tee` is required to have access rights with `sudo`.

2018-11-30 15:25 UTC, sergefdrv commented on .circleci/images/Dockerfile
> +  && echo 'source /opt/intel/sgxsdk/environment' | sudo tee -a /etc/profile > /dev/null
This container apparently works if one specifies `-l` option to the shell. It's up to you, to either keep `-l` option or add loader config file.

2018-12-03 11:32 UTC, ynamiki commented
Thanks for review. I have updated and open a new PR.

2018-12-03 11:32 UTC, closed without merging