[WIP] CircleCI: Use Pre-Built Image
hyperledger-labs/minbft pull request #60
Opened 2018-12-25 08:35 UTC by ynamiki

2018-12-26 23:16 UTC, nhoriguchi reviewed
Thanks for working on this. This commit seems to do multiple things, reverting #50, introducing environment variables, using curl instead of wget, so it might be better to split commit for bisectability. And some command like curl and apt-get have silent options which will help us to have cleaner log output.

2018-12-27 06:24 UTC, ynamiki commented
@Naoya-Horiguchi Thanks for your comments.

For the reversion, I intended not physical (`git revert 50c86aa` (#50)) but logical (meaning just we use a pre-built image again) revert since the Dockerfile has been updated after #50; I tried to port the Dockerfile to CircleCI's config with saving its styles (using environment variables, `curl`, etc.).

Can I hear a little more about an appropriate approach for this? 
Should I do `git revert 50c86aa` (this cause conflict), then cherry-picking commits from #55 for this PR and create another PR for changing style (using environment variables, `curl`, etc.)?

> And some command like curl and apt-get have silent options which will help us to have cleaner log output.

I will do in a revised version of this PR.

2018-12-27 08:06 UTC, Naoya-Horiguchi commented
> For the reversion, I intended not physical (git revert 50c86aa (#50)) but logical (meaning just we use a pre-built image again) revert since the Dockerfile has been updated after #50; I tried to port the Dockerfile to CircleCI's config with saving its styles (using environment variables, curl, etc.).
>
> Can I hear a little more about an appropriate approach for this?
> Should I do git revert 50c86aa (this cause conflict), then cherry-picking commits from #55 for this PR and create another PR for changing style (using environment variables, curl, etc.)?

Ah OK, so you don't have to separate the commit (that makes things more complicated). Please keep going with current approach. Thank you for the explanation!

2018-12-28 20:58 UTC, sergefdrv requested changes
Thanks for doing this! I think we can merge it after some small tweaks.

2018-12-28 20:58 UTC, sergefdrv commented on .circleci/config.yml
> +            sudo apt-get -y install build-essential python pkg-config
Using `apt-get -qq <cmd>` would make the log a bit less noisy.

2018-12-30 05:36 UTC, ynamiki commented
Thanks for comments! I revised this in #61.

2018-12-30 05:36 UTC, closed without merging