Post/issue1/tolerate f connection failure.v4
hyperledger-labs/minbft pull request #74
Opened 2019-03-07 08:37 UTC by Naoya-Horiguchi

Update #70 with following changes:

- used defer statement for channel close,
- undid using `WaitGroup` for simple synchronization,
- fixed `rootPath` in `sample/vendor/vendor.json`,
- improved dummy `ReplicaConnector` and `core/integration_test.go`.

2019-03-07 21:15 UTC, sergefdrv requested changes
Great job! I think we are nearly finished, just few more comments.

2019-03-07 21:15 UTC, sergefdrv commented on client/message-handling.go
>  		}
Could you please also remove the orphaned check for error at line 123?

2019-03-07 21:15 UTC, sergefdrv commented on sample/net/dummy/connector/replica-connector.go
> +	return &messageStreamHandler{replicaID, c}, nil
Now, we need to check if `replicaID < uint32(len(c.replicas))`.

2019-03-07 21:15 UTC, sergefdrv commented on sample/net/dummy/connector/replica-connector.go
> +	c.replicas[replicaID] <- replica
This line will only wake a single goroutine created by `messageStreamHandler.HandleMessageStream` and waiting on the channel (or block, if there is no one), whereas the API doesn't forbid calling `MessageStreamHandler.HandleMessageStream` multiple times on the same instance. The replica representation should behave in this case as if it was a real replica instance: establish multiple independent connections. 

Closing a channel, on the other hand, is a non-blocking broadcast signal to all goroutines waiting in receive operation on that channel. This issue should be easy to solve by using pre-allocated slices of replica instances and ready channels. Please look at https://github.com/hyperledger-labs/minbft/pull/70#discussion_r263558017.

2019-03-08 04:09 UTC, Naoya-Horiguchi commented on client/message-handling.go
>  		}
Fixed it.

2019-03-08 04:10 UTC, Naoya-Horiguchi commented on sample/net/dummy/connector/replica-connector.go
> +	return &messageStreamHandler{replicaID, c}, nil
Right, it helps us know what happens for invalid input.

2019-03-13 00:03 UTC, closed without merging