CI: Switch gometalinter to golangci-lint
hyperledger-labs/minbft pull request #78
Opened 2019-03-25 07:44 UTC by ynamiki

Gometalinter, a linter used in our CI, will be archived in April 2019: alecthomas/gometalinter#590.
This patch update the configuration to use [golangci-lint](https://github.com/golangci/golangci-lint), another linter introduced as an alternative.

This closes #71.

2019-03-26 20:30 UTC, sergefdrv requested changes
This linter is great! Thanks for adopting it for our project. I left some comments, though.

2019-03-26 20:30 UTC, sergefdrv commented on .circleci/config.yml
> +      GOLANGCI_LINT_URL: https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh
We might want to add another variable for the version of GolangCI-Lint we use:
```yml
GOLANGCI_LINT_VERSION: v1.15.0
```

2019-03-26 20:30 UTC, sergefdrv commented on Makefile
> +		./...
This command line becomes too busy. Let's use a [config file](https://github.com/golangci/golangci-lint/blob/v1.15.0/README.md#config-file) to specify the options.

2019-03-26 20:30 UTC, sergefdrv commented on .circleci/config.yml
> +            make lint || : allow failure
The linting issues mentioned in #79 are pretty trivial. Let's also resolve #79 in the scope of this PR.

2019-03-26 20:33 UTC, sergefdrv commented
This panel with two lines of CircleCI looks funny now :)
![image](https://user-images.githubusercontent.com/11386423/55031362-ba7c8e00-500e-11e9-93e5-180c8807ac55.png)

2019-03-27 01:49 UTC, closed without merging

2019-03-27 06:41 UTC, ynamiki commented
@sergefdrv 

> This panel with two lines of CircleCI looks funny now :)

It looks no problem.
We have a workflow named "build" and it consists of a job named "build" (i.e. same name).
The second line ("build") is the workflow and the last line ("ci/circleci: build") is a job.

GitHub shows both workflows and jobs in this page ("Conversation" tab) and shows only workflows in "Checks" tab.
I found this behavior in a PR of some other project such as `https://github.com/3scale/porta/pull/640/`.