Remove Dependency on GOPATH
hyperledger-labs/minbft pull request #88
Opened 2019-05-05 13:09 UTC by ynamiki

`keytool` and `peer` commands load libusig.signed.so from `$GOPATH/src/github.com/hyperledger-labs/minbft/usig/sgx/enclave` by default. Since we are now a Go module and independent from GOPATH, we should rethink this default value.

This patch updates the default path to find the library from a current directory. This patch also update Makefile to add `install` target to install the commands and the library into a single directory (by default, `sample/bin` and `sample/lib` respectively), and sample configuration files to try this project with minimal configuration wherever this project is placed on a file system.

Note: variables in the Makefile are defined based on [Makefile conventions](https://www.gnu.org/software/make/manual/html_node/Makefile-Conventions.html#Makefile-Conventions) with some simplification.

This closes #86.

2019-05-07 14:55 UTC, sergefdrv requested changes

2019-05-07 14:55 UTC, sergefdrv commented on Makefile
> +prefix := sample
Would be better to wrap it into `ifdef prefix` to allow supplying a custom installation directory.

2019-05-07 14:55 UTC, sergefdrv commented on Makefile
> +	@mkdir -p $(bindir)
It is recommended to use `install -d` in favor of `mkdir -p`. Alternatively, we can use `install -D` to copy files, which will create missing components of the destination file path.

2019-05-07 14:55 UTC, sergefdrv commented on .gitignore
> +/sample/build/
Please add `/sample/bin/` and `/sample/lib/`, as well.

2019-05-08 01:04 UTC, ynamiki commented on Makefile
> +prefix := sample
I think [a conditional variable assignment operator `?=`](https://www.gnu.org/software/make/manual/html_node/Setting.html) (i.e.  `prefix ?= sample`) meets our requirements. Do you have any concerns about using this?

2019-05-08 07:38 UTC, sergefdrv commented on Makefile
> +prefix := sample
You are right, `?=` would be much cleaner :+1:

2019-05-08 08:04 UTC, ynamiki commented
@sergefdrv Thanks for your comments. I have updated the code in #89.

2019-05-08 08:04 UTC, closed without merging